### PR TITLE
Added transform adjustment

### PR DESCRIPTION
**Pull request by stevengeeky**
Applied Qform matrix to convert to LSA

### CODE REVIEW

**Comment by kitchell** [comment]
Is there a way to make the adjustment in the viewer? I worry this will put the meshes out of alignment with other data.

**Comment by stevengeeky** [comment]
Will the output surfaces be used for something other than the visualization?
This change shouldn't affect other meshes that are displayed using ui-3dsurfaces. The sample data used for the viewer is aligned in a way that no adjustment has to be made on the viewer, but the output from this app is not aligned the same way.

**Comment by stevengeeky** [comment]
I can remove the axis swapping and place it on the viewer side, but the application of the Qform matrix should transform the data into LAS format (which I thought was standard). If not, then I can remove both and just place them in the visualizer

**Comment by stevengeeky** [comment]
Okay, I moved the axis swapping to the visualization side, but kept the Qform application

**Comment by kitchell** [comment]
ok! merging

**Pull request merged**
